### ISSUE TITLE
mentor notes

### ISSUE THREAD

**Issue by gtim** [SandorTeleki/dom_inspector_bot#7]
- [x] listen to `/setnote [class] [id] notes`
  - e.g. `/setnote item 23 useful against high-prot thugs`
  - I think ID is preferrable to name as it avoids name collisions (bane blade, gygja etc) and is easier to parse (no spaces)
- [x] check user permissions to hard-coded trusted user whitelist
- [x] record notes in SQLite database
  - table suggestion: class, name, note, written_time, written_by_user. 
- [x] include notes in embed answer from `/item`, `/spell` etc
- [x] store history, e.g. in another table that does not delete old entries.

**Comment by SandorTeleki** [comment]
To alllow each guild (server) to have their own mentor notes, the table will probably have the following columns:
class, ID, name, note, guild (or guildID), written_time, written_by_user

**Comment by SandorTeleki** [comment]
Task 1 complete: bot is now listening to "?note" command. 
Error handling added to check command syntax, note length (both a min and a max) and that the set ID actually matches an existing thing (so we don't create mentor notes for items that do not exist)

**Comment by SandorTeleki** [comment]
Task 3 and 5 complete: two tables have been created. mentor_notes was created to store the current mentor note. mentor_logs was created to store a full history of mentor note INSERTs and UPDATEs. 

Also added error checking for correct command synthax, min and max length of mentor note, and a check to see if the ID exists. All these steps are taken before writing anything to the db tables.

**Comment by SandorTeleki** [comment]
Task 2 complete: the ?note command checks if the user who used the command is whitelisted, and if they aren't, it returns an error message to the user. Also created the same for channels (so that the note command is only used in certain channels - to avoid clogging up other channels and to avoid confusion).

**Comment by SandorTeleki** [comment]
Task 4 complete: mentor notes will appear for all embeds, but only in the whitelisted channel (and the guild that created it) while beta testing is in progress.

**Comment by SandorTeleki** [comment]
Mentor notes fully implemented and in beta testing. The commit was: https://github.com/SandorTeleki/dom_inspector_bot/commit/58c14249d6cbeb6df51b1365670c97c7e6452920
